# airflow-values.yaml

# Set the executor to KubernetesExecutor
executor: KubernetesExecutor

# Configuration for the Kubernetes Executor
kubernetes:
  # If you have multiple worker node pools, you can specify tolerations and node selectors
  # to schedule task pods on specific nodes.
  workerTolerations: []
  #   - key: "group"
  #     operator: "Equal"
  #     value: "data-processing"
  #     effect: "NoSchedule"y

# Resource allocation for the webserver
webserver:
  defaultUser:
    enabled: true
    role: "Admin"
    username: "admin"
    # Set your own password here before installing
    password: "Admin123"

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

# Resource allocation for the scheduler
scheduler:
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

# Configure DAGs to be synced from a git repository
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/alamak202/airflow-101.git" # Replace with your DAGs repository
    branch: "main" # Or your desired branch
    subPath: "dag_examples"
    # If your repository is private, you can use a secret:
    # credentialsSecret: "my-git-credentials-secret"

