# minio-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: airflow-minio-connection-secret
  namespace: airflow
type: Opaque
# Use 'stringData' to avoid having to Base64 encode your secret.
# Kubernetes will handle the encoding automatically.
stringData:
  # IMPORTANT: Replace with your actual decoded credentials
  connection: 'aws://alamak:aBcDeF12345@?endpoint_url=http%3A%2F%2Fminio.airflow.svc.cluster.local%3A9000'